services:
  - type: web
    name: fashion-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://fashion-frontend-imqb.onrender.com
      - key: VNP_TMN_CODE
        value: EFUXNX9W
      - key: VNP_HASH_SECRET
        value: BN7IT7FUUG2X8UUIAFH35ZNE4YJ9KH3G
      - key: VNP_URL
        value: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - key: VNP_RETURN_URL
        value: https://fashion-backend-93lh.onrender.com/api/payment/vnpay-return
      - key: VNP_IPN_URL
        value: https://fashion-backend-93lh.onrender.com/api/payment/vnpay-ipn
      - key: MOMO_PARTNER_CODE
        value: MOMOBKUN20180529
      - key: MOMO_ACCESS_KEY
        value: klm05TvNBzhg7h7j
      - key: MOMO_SECRET_KEY
        value: at67qH6mk8w5Y1nAyMoYKMWACiEi2bsa
      - key: MOMO_API_URL
        value: https://test-payment.momo.vn/v2/gateway/api/create
      - key: MOMO_RETURN_URL
        value: https://fashion-backend-93lh.onrender.com/api/payment/momo-return
      - key: MOMO_IPN_URL
        value: https://fashion-backend-93lh.onrender.com/api/payment/momo-ipn
    region: singapore

  - type: web
    name: fashion-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://fashion-backend-93lh.onrender.com
      - key: NODE_VERSION
        value: 20
    region: singapore
